import {
  PuzzlePieceIcon as PuzzlePieceOutline,
  FunnelIcon as FunnelOutline,
  UserGroupIcon as UserGroupOutline,
  ArrowsRightLeftIcon as ArrowsRightLeftOutline,
  ExclamationTriangleIcon as ExclamationTriangleOutline,
  CurrencyDollarIcon as CurrencyDollarOutline,
  ClockIcon as ClockOutline,
  ShieldExclamationIcon as ShieldExclamationOutline,
  ArrowsPointingOutIcon as ArrowsPointingOutOutline,
  RocketLaunchIcon as RocketLaunchOutline,
  ArrowPathIcon as ArrowPathIconOutline,
  SquaresPlusIcon as SquaresPlusIconOutline,
  WrenchScrewdriverIcon as WrenchScrewdriverIconOutline,
  AcademicCapIcon as AcademicCapIconOutline,
  SparklesIcon as SparklesIconOutline,
  CircleStackIcon as CircleStackIconOutline,
  CogIcon as CogIconOutline,
  CloudIcon as CloudIconOutline,
  ServerStackIcon as ServerStackIconOutline,
    CloudArrowUpIcon as CloudArrowUpOutline,
  ChartBarIcon as ChartBarIconOutline,
  CodeBracketSquareIcon as CodeBracketSquareIconOutline ,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconOutline,
  CameraIcon as CameraIconOutline,

} from "@heroicons/react/24/outline";

import {
  PuzzlePieceIcon as PuzzlePieceSolid,
  FunnelIcon as FunnelSolid,
  UserGroupIcon as UserGroupSolid,
  ArrowsRightLeftIcon as ArrowsRightLeftSolid,
  ExclamationTriangleIcon as ExclamationTriangleSolid,
  CurrencyDollarIcon as CurrencyDollarSolid,
  ClockIcon as ClockSolid,
  ShieldExclamationIcon as ShieldExclamationSolid,
  ArrowsPointingOutIcon as ArrowsPointingOutSolid,
  RocketLaunchIcon as RocketLaunchSolid,
  CloudArrowUpIcon as CloudArrowUpSolid,
  ChartBarIcon as ChartBarIconSolid,
  CodeBracketSquareIcon as CodeBracketSquareIconSolid ,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconSolid,
  CameraIcon as CameraIconSolid,
  ArrowPathIcon as ArrowPathIconSolid,
  SquaresPlusIcon as SquaresPlusIconSolid,
  WrenchScrewdriverIcon as WrenchScrewdriverIconSolid,
  AcademicCapIcon as AcademicCapIconSolid,
  SparklesIcon as SparklesIconSolid,
  CircleStackIcon as CircleStackIconSolid,
  CogIcon as CogIconSolid,
    CloudIcon as CloudIconSolid,
  ServerStackIcon as ServerStackIconSolid,
} from "@heroicons/react/24/solid";

import React from "react";

export const iconMapOutline = {
  PuzzlePiece: PuzzlePieceOutline,
  Funnel: FunnelOutline,
  UserGroup: UserGroupOutline,
  ArrowsRightLeft: ArrowsRightLeftOutline,
  ExclamationTriangle: ExclamationTriangleOutline,
  CurrencyDollar: CurrencyDollarOutline,
  Clock: ClockOutline,
  ShieldExclamation: ShieldExclamationOutline,
  ArrowsPointingOut: ArrowsPointingOutOutline,
  RocketLaunch: RocketLaunchOutline,
    CloudArrowUp: CloudArrowUpOutline,
  ChatBubbleLeftRight: ChatBubbleLeftRightIconOutline,
  ChartBarIconOutline: ChartBarIconOutline,
CodeBracketSquare: CodeBracketSquareIconOutline,
  Camera: CameraIconOutline,
  AcademicCap: ArrowPathIconOutline,
  WrenchScrewdriver: SquaresPlusIconOutline,
  SquaresPlus: WrenchScrewdriverIconOutline,
  ArrowPath: AcademicCapIconOutline,
  Sparkles: SparklesIconOutline,
  CircleStack: CircleStackIconOutline,
  Cog: CogIconOutline,
      Cloud: CloudIconOutline,
  ServerStack: ServerStackIconOutline,
};

export const iconMapSolid = {
  PuzzlePiece: PuzzlePieceSolid,
  Funnel: FunnelSolid,
  UserGroup: UserGroupSolid,
  ArrowsRightLeft: ArrowsRightLeftSolid,
  ExclamationTriangle: ExclamationTriangleSolid,
  CurrencyDollar: CurrencyDollarSolid,
  Clock: ClockSolid,
  ShieldExclamation: ShieldExclamationSolid,
  ArrowsPointingOut: ArrowsPointingOutSolid,
  RocketLaunch: RocketLaunchSolid,
  CloudArrowUp: CloudArrowUpSolid,
  ChartBar: ChartBarIconSolid,
  CodeBracketSquare: CodeBracketSquareIconSolid,
  Camera: CameraIconSolid,
  ChatBubbleLeftRight: ChatBubbleLeftRightIconSolid,
  AcademicCap: ArrowPathIconSolid,
  WrenchScrewdriver: SquaresPlusIconSolid,
  SquaresPlus: WrenchScrewdriverIconSolid,
  ArrowPath: AcademicCapIconSolid,
  Sparkles: SparklesIconSolid,
  CircleStack: CircleStackIconSolid,
  Cog: CogIconSolid,
        Cloud: CloudIconSolid,
  ServerStack: ServerStackIconSolid,
};

export type IconNameOutline = keyof typeof iconMapOutline;
export type IconNameSolid = keyof typeof iconMapSolid;

export const FallbackIconOutline = ExclamationTriangleOutline;
export const FallbackIconSolid = ExclamationTriangleSolid;
